config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :organisers
  resources :events
  devise_for :users, skip: [:registerable, :recoverable]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  get '/download_calendar_event', to: 'home#download_calendar_event'
end

app/models/organiser.rb
class Organiser < ApplicationRecord
  has_and_belongs_to_many :events, class_name: "Event", join_table: 'event_organisers'
  validates :name, uniqueness: true, presence: true
end

app/controllers/organisers_controller.rb
class OrganisersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_organiser, only: [:show, :edit, :update, :destroy]

  # GET /organisers
  # GET /organisers.json
  def index
    @organisers = Organiser.all
  end

  # GET /organisers/1
  # GET /organisers/1.json
  def show
  end

  # GET /organisers/new
  def new
    @organiser = Organiser.new
  end

  # GET /organisers/1/edit
  def edit
  end

  # POST /organisers
  # POST /organisers.json
  def create
    @organiser = Organiser.new(organiser_params)

    respond_to do |format|
      if @organiser.save
        format.html { redirect_to @organiser, notice: 'Organiser was successfully created.' }
        format.json { render :show, status: :created, location: @organiser }
      else
        format.html { render :new }
        format.json { render json: @organiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisers/1
  # PATCH/PUT /organisers/1.json
  def update
    respond_to do |format|
      if @organiser.update(organiser_params)
        format.html { redirect_to @organiser, notice: 'Organiser was successfully updated.' }
        format.json { render :show, status: :ok, location: @organiser }
      else
        format.html { render :edit }
        format.json { render json: @organiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisers/1
  # DELETE /organisers/1.json
  def destroy
    @organiser.destroy
    respond_to do |format|
      format.html { redirect_to organisers_url, notice: 'Organiser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organiser
      @organiser = Organiser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organiser_params
      params.require(:organiser).permit(:name)
    end
end

app/helpers/organisers_helper.rb
module OrganisersHelper
end

app/views/organisers/_form.html.erb
<%= form_with(model: organiser, local: true) do |form| %>
  <% if organiser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organiser.errors.count, "error") %> prohibited this organiser from being saved:</h2>

      <ul>
      <% organiser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :organiser_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organisers/edit.html.erb
<main class="container page-padding--bottom">
  <h1>Editing Organiser</h1>

  <%= render 'form', organiser: @organiser %>

  <%= link_to 'Show', @organiser %> |
  <%= link_to 'Back', organisers_path %>
</main>

app/views/organisers/index.html.erb
<p id="notice"><%= notice %></p>
<main class="container page-padding--bottom">

  <%= render "shared/menu" %>

  <h1>Organisers</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @organisers.each do |organiser| %>
        <tr>
          <td><%= organiser.name %></td>
          <td><%= link_to 'Show', organiser %></td>
          <td><%= link_to 'Edit', edit_organiser_path(organiser) %></td>
          <td><%= link_to 'Destroy', organiser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Organiser', new_organiser_path %>
</main>

app/views/organisers/new.html.erb
<main class="container page-padding--bottom">
  <h1>New Organiser</h1>

  <%= render 'form', organiser: @organiser %>

  <%= link_to 'Back', organisers_path %>
</main>

app/views/organisers/show.html.erb
<p id="notice"><%= notice %></p>
<main class="container page-padding--bottom">
  <p>
    <strong>Name:</strong>
    <%= @organiser.name %>
  </p>

  <%= link_to 'Edit', edit_organiser_path(@organiser) %> |
  <%= link_to 'Back', organisers_path %>
</main>